# Generated by Django 4.1.2 on 2022-11-06 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='chart',
            name='ticker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='charts.ticker'),
            preserve_default=False,
        ),
    ]
