# Generated by Django 4.1.2 on 2022-11-11 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0006_remove_ticker_currency_remove_ticker_timezone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='stock_exchange',
        ),
        migrations.AddField(
            model_name='ticker',
            name='exchange',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='charts.exchange'),
            preserve_default=False,
        ),
    ]
