# Generated by Django 4.1.2 on 2022-11-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0007_remove_ticker_stock_exchange_ticker_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='website',
            field=models.CharField(max_length=50),
        ),
    ]
